### ISSUE TITLE
是否已经适合在生产环境中使用？

### ISSUE THREAD

**Issue by dingyiming** [hubcarl/easywebpack-vue#1]
- 看到 egg + webpack + vue 的方式很适合我接下来的一个系统的开发，想直接用easywebpack-vue 作为前端基础方案进行使用，主要是做三套管理平台整合成一套后台管理系统，目前是否已经适合在生产环境中使用？ 
- 作者是否已经有成功的实践案例？
- 谢谢。

**Comment by hubcarl** [comment]
@dingyiming  有多个实际的线上应用，单页面，多页面，服务端渲染都有实践，请放心使用。服务端多页面渲染，项目骨架请参考：https://github.com/hubcarl/egg-vue-webpack-boilerplate， 同时支持前端渲染
