### ISSUE TITLE
小白问个问题 关于url的

### ISSUE THREAD

**Issue by wzs28150** [hubcarl/easywebpack-vue#2]
这我想循环图片 
![tim 20180504155147](https://user-images.githubusercontent.com/21290257/39617690-4213a342-4fb3-11e8-841d-00a8d900304b.png)
mocks 里这个数据路径怎么给- - 怎么能 自动转到 public下呢
![image](https://user-images.githubusercontent.com/21290257/39617764-8c6945b4-4fb3-11e8-8b33-b42ab50b52fc.png)

**Comment by songyazhao** [comment]
绑定的src应该用绝对路径，而非相对

**Comment by hubcarl** [comment]
@wzs28150 可以在vue 代码里面 通过require 引入，然后就可以数据绑定了

**Comment by wzs28150** [comment]
谢谢大家帮忙~
